"""
This is a setup.py script (originally) generated by py2applet.

The primary purpose of this script is to generate a self-contained, standalone bundle 
for PhysiCell Studio for MacOS.

Usage:
    python setup.py py2app

More detailed steps:
* Create a (minimal) Python distribution for the Studio:
  * install Miniconda3
  * create/activate a venv
  * (myenv-conda) pip (or conda) install PyQt5       # for just the Model Builder (without Studio plotting)
  * (myenv-conda) pip (or conda) install matplotlib, pandas, scipy   # for Studio plotting

If you've also attempted to use "pyinstaller" on MacOS, remove it:
* pip uninstall pyinstaller  # https://github.com/ronaldoussoren/py2app/issues/462#issuecomment-1192361635

* (myenv-conda) M1P~/git/studio_bundle/scripts$ rm -rf  dist build   # if they exist
* (myenv-conda) python setup.py py2app

* Apparently we need to manually copy over libs before trying to run the app:
    pushd dist/pmb.app/Contents/Frameworks
    cp ~/opt/miniconda3/envs/myenv-conda/lib/libffi.7.dylib .
    cp ~/opt/miniconda3/envs/myenv-conda/lib/libiomp5.dylib .
    cp ~/opt/miniconda3/envs/myenv-conda/lib/libgfortran.5.dylib .
    cp ~/opt/miniconda3/envs/myenv-conda/lib/libquadmath.0.dylib .
    cp ~/opt/miniconda3/envs/myenv-conda/lib/libgcc_s.1.1.dylib .
    pushd

* Finally, try to run the app:
  (myenv-conda) M1P~/git/studio_bundle/scripts$ ./dist/pmb.app/Contents/MacOS/pmb   # forced to do Studio
  (myenv-conda) M1P~/git/studio_bundle/scripts$ ./dist/pmb.app/Contents/MacOS/pmb --studio  # now in pmb.py
  (myenv-conda) M1P~/git/studio_bundle/scripts/dist$ open pmb.app



Author: Randy Heiland

"""

from setuptools import setup
from glob import glob

APP = ['pmb.py']
DATA_FILES = []

# this will provide a non-Dark mode rendering of the GUI on MacOS
OPTIONS = {"plist" : {"NSRequiresAquaSystemAppearance": True},}


setup(
    app=['pmb.py'],
    data_files=['physicell_logo_200px.png',
        ('../data', glob('../data/*.xml')),
        ('../data', glob('../data/*.bnd')),
        ('../data', glob('../data/*.cfg')),
    ],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],

   py_modules=['config_tab','microenv_tab','populate_tree_cell_defs','cell_def_tab','user_params_tab','ics_tab','run_tab','vis_tab','legend_tab','pyMCDS_cells'],
#    py_modules=['config_tab','microenv_tab','cell_def_tab','user_params_tab','ics_tab','run_tab','legend_tab'],
    # py_modules=['config_tab','microenv_tab','cell_def_tab','user_params_tab'],
)
